const books = [
    {
        "formato": "Libro f\u00edsico",
        "autor": "Joyce dunbar",
        "editorial": "Edeb\u00e9",
        "categoria": "Infantil y juvenil",
        "anio": "2007",
        "idioma": "Espa\u00f1ol",
        "encuadernacion": "Tapa blanda",
        "ISBN13": "978842301",
        "titulo": "Software la Superbabosa",
        "FotoLibro": "https://images.cdn2.buscalibre.com/fit-in/180x180/1f/a6/1fa666e0f93fb0bc63c4c214188f3a46.jpg",
        "nPaginas": "104",
        "pedidos": "0",
        "FechaDevolucion": "0",
    },
    {
        "formato": "Libro f\u00edsico",
        "autor": "Flores masias, eward; huarote zegarra, raul",
        "editorial": "Fondo editorial universidad c\u00e9sar vallejo",
        "categoria": "Ingenieria",
        "anio": "2019",
        "idioma": "Espa\u00f1ol",
        "encuadernacion": "Tapa blanda",
        "ISBN13": "978612402",
        "titulo": "Gestion de proyecto de Software",
        "FotoLibro": "https://images.cdn1.buscalibre.com/fit-in/180x180/20/82/2082a4e5a59dcf7e8531feb8e488c30b.jpg",
        "nPaginas": "128",
        "pedidos": "0",
        "FechaDevolucion": " ",
    },
    {
        "formato": "Libro f\u00edsico",
        "autor": "Vallejos,  mariela",
        "editorial": "Cuarto propio",
        "categoria": "Ciencias humanas",
        "anio": "2023",
        "idioma": "Espa\u00f1ol",
        "encuadernacion": "Tapa blanda",
        "ISBN13": "978956303",
        "titulo": "Reemplazada por un Software",
        "FotoLibro": "https://images.cdn3.buscalibre.com/fit-in/180x180/a0/b2/a0b2c729a04d61a9348942dff8dbaa39.jpg",
        "nPaginas": "214",
        "pedidos": "0",
        "FechaDevolucion": "0",
    },
    {
        "formato": "Libro f\u00edsico",
        "autor": "Ian sommerville",
        "editorial": "Pearson",
        "categoria": "Computadoras y tecnolog\u00eda",
        "anio": "2011",
        "idioma": "Espa\u00f1ol",
        "encuadernacion": "Tapa blanda",
        "ISBN13": "978607304",
        "titulo": "Ingenier\u00eda de Software",
        "FotoLibro": "https://images.cdn3.buscalibre.com/fit-in/180x180/f8/78/f878362b2a6c71f5e7125eafff09a82c.jpg",
        "nPaginas": "792",
        "pedidos": "0",
        "FechaDevolucion": "0",
    },
    {
        "formato": "Libro f\u00edsico",
        "autor": "Juan f. mateos",
        "editorial": "Anaya multimedia",
        "anio": "2008",
        "idioma": "Espa\u00f1ol",
        "encuadernacion": "Tapa blanda",
        "ISBN13": "978844105",
        "categoria": "Dispositivos lectores de libros digitales",
        "titulo": "Edici\u00f3n de Medios Digitales con Software Libre (Tratamiento de V\u00eddeo, Audio e Imagen con Software Gratuito) (Gu\u00edas Pr\u00e1cticas)",
        "FotoLibro": "https://images.cdn1.buscalibre.com/fit-in/180x180/b2/4f/b24f5a1c7adddcc154ad324483235c72.jpg",
        "nPaginas": "368",
        "pedidos": "0",
        "FechaDevolucion": "0",
    },
    {
        "formato": "Libro f\u00edsico",
        "autor": "Peter h\u00fcnermann",
        "editorial": "Universidad alberto hurtado",
        "categoria": "Ciencias humanas",
        "anio": "2014",
        "idioma": "Espa\u00f1ol",
        "encuadernacion": "Tapa blanda",
        "ISBN13": "978956306",
        "titulo": "El El Vaticano II como software de la iglesia actualii",
        "FotoLibro": "https://images.cdn1.buscalibre.com/fit-in/180x180/98/f8/98f851577377e72513d555512f55617f.jpg",
        "nPaginas": "348",
        "pedidos": "0",
        "FechaDevolucion": "0",
    },
    {
        "formato": "Libro f\u00edsico",
        "autor": "Joyce dunbar",
        "editorial": "Edebe",
        "categoria": "Infantil",
        "anio": "1990",
        "idioma": "Espa\u00f1ol",
        "encuadernacion": "Tapa blanda",
        "ISBN13": "978842307",
        "titulo": "Goodreads Software y el estupor inform\u00e1tico",
        "FotoLibro": "https://images.cdn1.buscalibre.com/fit-in/180x180/ef/e8/efe821552b8ec7f23174fbfff1755870.jpg",
        "nPaginas": "100",
        "pedidos": "0",
        "FechaDevolucion": "0",
    },
    {
        "formato": "Libro f\u00edsico",
        "autor": "Joyce dunbar",
        "editorial": "Edebe",
        "categoria": "Literatura inglesa",
        "anio": "1992",
        "idioma": "Espa\u00f1ol",
        "encuadernacion": "Tapa blanda",
        "ISBN13": "978842308",
        "titulo": "Software y el Arte de Hacer Media",
        "FotoLibro": "https://images.cdn1.buscalibre.com/fit-in/180x180/46/f2/46f283d23180e936bb251655dbc699ae.jpg",
        "nPaginas": "120",
        "pedidos": "0",
        "FechaDevolucion": "0",
    },
    {
        "formato": "Libro f\u00edsico",
        "autor": "Joyce dunbar",
        "editorial": "Edebe",
	"categoria": "Literatura inglesa",
        "anio": "2004",
        "idioma": "Espa\u00f1ol",
        "encuadernacion": "Tapa blanda",
        "ISBN13": "978842309",
        "titulo": "Software, La Superbabosa",
        "FotoLibro": "https://images.cdn3.buscalibre.com/fit-in/180x180/21/6f/216f45ed6c90bd079941db392d9f9a3a.jpg",
        "nPaginas": "186",
        "pedidos": "0",
        "FechaDevolucion": "0",
    },
    {
        "formato": "Libro f\u00edsico",
        "autor": "David squires,david mcdougall",
        "editorial": "Morata",
        "anio": "2001",
        "idioma": "Espa\u00f1ol",
        "encuadernacion": "Tapa blanda",
        "ISBN13": "978847110",
        "categoria": "Recursos y materiales did\u00e1cticos para docentes                                            Tecnolog\u00edas educativas",
        "titulo": "Como Elegir y Utilizar Software Educativo",
        "FotoLibro": "https://images.cdn2.buscalibre.com/fit-in/180x180/5c/25/5c2576ff6c47d96229b0123281eabcf7.jpg",
        "nPaginas": "176",
        "pedidos": "0",
        "FechaDevolucion": "0",
    }
];
module.exports = books;
